### ISSUE TITLE
web版在线测试打不开

### ISSUE THREAD

**Issue by ahthabc** [CarGuo/gsy_flutter_demo#22]
main.dart.js:11226 Uncaught LateInitializationError: Field '_defaultBinaryMessenger' has already been initialized.
    at Object.wrapException (main.dart.js:11226:17)
    at Object._lateWriteOnceCheck (main.dart.js:12563:17)
    at WidgetsFlutterBinding.set$_defaultBinaryMessenger (main.dart.js:133871:9)
    at WidgetsFlutterBinding.initInstances$0 (main.dart.js:138222:13)
    at WidgetsFlutterBinding.initInstances$0 (main.dart.js:138244:13)
    at WidgetsFlutterBinding.initInstances$0 (main.dart.js:138301:13)
    at WidgetsFlutterBinding.initInstances$0 (main.dart.js:138317:13)
    at WidgetsFlutterBinding.initInstances$0 (main.dart.js:138366:13)
    at WidgetsFlutterBinding.BindingBase$0 (main.dart.js:101450:12)
    at Object.WidgetsFlutterBinding$ (main.dart.js:37181:10)

**Comment by CarGuo** [comment]
不好意思，今天一直在做测试，大概是这个 https://juejin.cn/post/7079062175532187656?share_token=9baca303-1972-472b-b9ea-cda7e3d8e1b2  现在已经修复
